package org.jooq.impl;

enum DDLStatementType {
   CREATE_INDEX,
   CREATE_SEQUENCE,
   CREATE_TABLE,
   CREATE_VIEW,
   CREATE_SCHEMA,
   DROP_INDEX,
   DROP_SEQUENCE,
   DROP_TABLE,
   DROP_VIEW,
   DROP_SCHEMA;
}
